### ISSUE TITLE
r-studio-cpu notebook package update

### ISSUE THREAD

**Issue by chritter** [StatCan/kubeflow-containers-desktop#16]
Hello,
I would suggest to have the following packages installed/updated with RStudio to avoid having to do that when starting with RStudio. These messages pop up when using RStudio: caTools and bitops

See below for the messages.

![image](https://user-images.githubusercontent.com/15911039/85041819-6f412480-b158-11ea-996c-ebb5a15105c1.png)

**Comment by frazs** [comment]
Just to confirm since you're in the ml-workspace/remote-desktop repo, is this for r-studio-cpu or ml-workspace-rstudio/remote-desktop-r?

**Comment by chritter** [comment]
@frazs I am in 
![image](https://user-images.githubusercontent.com/15911039/85710242-102d6380-b6b4-11ea-875f-09803509efc9.png)
Thanks!

**Comment by frazs** [comment]
@blairdrummond I think this is the one you built. But if nobody's available to handle this I can poke around, let me know.
