### ISSUE TITLE
simple image viewer on ml-workspace geo image

### ISSUE THREAD

**Issue by chritter** [StatCan/kubeflow-containers-desktop#17]
Hello,
We definitely would need a simple, fast image viewer such as the default Eye of Gnome (https://wiki.gnome.org/Apps/EyeOfGnome) on the geo image. I was surprised to find that it is not installed. QGIS is a heavier program, not suitable for quick lookup of images.
Thanks

**Comment by blairdrummond** [comment]
`feh` is a simple and small program.

**Comment by chritter** [comment]
@blairdrummond I would suggest to have ```feh``` as an addition to the default Ubuntu viewer Eye of Gnome, to be added.

**Comment by frazs** [comment]
I tested both. Unfortunately `feh` seems to be glitchy in this environment when it comes to zoom and window size for large images. `eog` works fine though. I'll just add that one unless there's a particular need for `feh`.

**Comment by chritter** [comment]
@frazs No need for `feh`. Thanks!
