### ISSUE TITLE
ci: Add secrets

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers-desktop#26]
The following secrets need to be added to this repository, corresponding to the ACR `k8scc01covidacr`:

1. REGISTRY_USERNAME with ACR username
2. REGISTRY_PASSWORD with ACR Password
3. AZURE_CREDENTIALS with the output of `az ad sp create-for-rbac --sdk-auth`

**Comment by zachomedia** [comment]
This has been completed!
