### ISSUE TITLE
Libreoffice Calc

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers-desktop#40]
Would we be able to install Libreoffice Calc on the desktop image? I'm thinking that a Spreadsheet program could be helpful as analysts may bee to wrangle Excel files.

I think there's also some merit to having Libreoffice Writer, but Calc is probably most important.

CC @brendangadd @frazs

**Comment by frazs** [comment]
I don't think it's possible install LibreOffice components individually

Edit: It is, but not advised - apparently doesn't lead to significant space savings (kilobytes) and can lead to dependency issues. Might be outdated info though, will test.
