### ISSUE TITLE
Move home_nbuser_default out of /tmp/

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers-desktop#42]
When a user attaches a persistent volume to their Remote Desktop container on Kubeflow, `/home/jovyan` is overwritten. Therefore, one of the last build steps of the base Remote Desktop image is to copy everything from `/home/{NB_USER}` (which is currently `/home/jovyan/` into `/tmp/home_nbuser_default`. Then, in `init.sh`, when the container runs, `/tmp/home_nbuser_default/` is copied back into `/home/{NB_USER}` (which at this point would have already been replaced by the persistent volume). 

The issue is that it is common for various kinds of cleanup code (including the image's own `clean-layer.sh`) to remove everything in `/tmp/`. This causes problems when this occurs in any image that inherits the base Remote Desktop image.

`/tmp/` was originally selected as the location of `home_nbuser_default` so that it could be deleted, because to delete a directory a user must have write permissions to the parent directory.

Let's find a better place for `home_nbuser_default`. This will need to be updated in the base Dockerfile, init.sh, r/r-studio-desktop.sh, and geomatics/qgis.sh off the top of my head, but double check if there are other locations. 

Given that, if I understand correctly, when it comes to storage on nodes, everything that remains identical to the built image is stored once and shared across all containers, but differences inside containers are each stored separately... Then there may not be any benefit to removing `home_nbuser_default` after it is copied, so it could go somewhere where the user doesn't have permissions to the parent directory.

I don't recall if there were any issues with `mv` instead of `cp` (other than the parent directory permissions that are relevant to `rm`) so that might be worth a check as well, if it still works and can save space (including for the initial `/home/{NB_USER}` -> `home_nbuser_default`)

**Comment by wg102** [comment]
The code should be fixed by the pull request, but as mentioned in the PR, it has been tested only locally. A more thorough test, including docker push should be done before closing the ticket. It seems some more specific permissions are needed.
For complete instructions on how to test, check this [document](https://docs.google.com/document/d/1fvH21ll_syk1au-WjA20IQZfod_zqYfq7ORzJkhIlzM/edit#heading=h.173fbnwogbic), in the Manual build testing section.

**Comment by frazs** [comment]
A more up-to-date & vpn-accessible version of said document is [over here](https://github.com/StatCan/daaas/wiki/Remote-Desktop-Dev-Notes#manual-build-for-testing), possibly pending another location in the future (e.g. could make sense as a wiki for this repo)
